#!/bin/sh
#  $Id: texpad,v 1.1 2002/02/24 18:21:58 jfine Exp $
#  texpad: an interactive TeX interpreter

# Copyright (c) Jonathan Fine, 2002
# mailto:jfine@activetex.org

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License; either version
# 2 of the License, or (at your option) any later version.

# $Log: texpad,v $
# Revision 1.1  2002/02/24 18:21:58  jfine
# Initial revision
#
    
if [ $# -gt 0 ] ; then
    echo "texpad: an interactive TeX interpreter"
    exit 0
fi

# get xdvi started
tex '\shipout\hbox{\bf Welcome to \TeX pad v0.1}\end'
mv texput.dvi 1.dvi
xdvi 1.dvi -paper 1ptx1pt -geometry 500x372 -s 3 &
XDVI_PID=$!
sleep 1 # give xdvi a chance to get going, before it gets a signal

# get dvichop started
rm -f texpad.dvi
mkfifo texpad.dvi
dvichop texpad.dvi & 

# do we have ipc enabled?
tex -help | grep -q ipc
HAVE_IPC=$?

# if we do have ipc, use it
if [ ${HAVE_IPC} -eq '0' ] ; then 
  IPC=-ipc
  NOFLUSH='\let\DviFlush\relax'
else
  IPC=
  NOFLUSH=
fi

# start the TeX daemon
tex ${IPC} texpad.sty "${NOFLUSH} \\DviOpen \\texpad{1}{${XDVI_PID}} \\DviClose \\end"

# clean up afterwards
kill ${XDVI_PID}
rm -f texpad.dvi
rm -f texpad.tex

# end of texpad
